### ISSUE TITLE
I am getting an error with the links

### ISSUE THREAD

**Issue by ahande123** [lgcolella/gatsby-starter-developer-blog#13]
Once I go to the About page or the tags page or a particular tag, I can't use any of the links in the header.

http://localhost:8000/tag

I get links like these which all go to the 404 page

http://localhost:8000/tag/tag
http://localhost:8000/tag/about
http://localhost:8000/tag/tag/angular

**Comment by luigi-colella** [comment]
Hi @ahande123 and thank you for the issue because it can improve the project.

Since I wasn't able to replicate the issue neither on my local environment nor on [production](https://lgcolella.github.io/gatsby-starter-developer-blog/), I would ask you:

1. Are there errors during build phase ? (Before to do this check, I would suggest to clone the repository, install dependencies and build it again from scratch in order to avoid cache issues or similar)
2. Are you able the replicate the issue on the [production](https://lgcolella.github.io/gatsby-starter-developer-blog/) ?
3. Which browsers are you able to replicate the issue on?
4. Since you navigate from http://localhost:8000, are there errors in the browser console? If yes, can you share them?
5. Which OS are you using? Which version of Node.js, NPM or Yarn are you using?

**Comment by lgcolella** [comment]
Issue closed since there was any response by its author.

**Comment by luigi-colella** [comment]
Issue closed since there was any response by its author.
