### ISSUE TITLE
GIF support in markdown

### ISSUE THREAD

**Issue by ahmedkrmn** [lgcolella/gatsby-starter-developer-blog#8]
Hi,
First of all, thanks for the great effort that you've put into this starter.

The only problem that I'm facing is that I can't use GIFs in my blog posts.
Images work fine, but GIFs show a corrupted image icon and nothing is displayed.

I tried and used [gatsby-remark-copy-linked-files](https://www.gatsbyjs.org/packages/gatsby-remark-copy-linked-files/?=copy-#gatsby-remark-copy-linked-files) plugin. It displayed the GIFs but with removing all the styling in the page as well as normal images.

**Comment by luigi-colella** [comment]
Hi,

thank you for the appreciating.

I added the mentioned plugin and it seems to work fine. https://github.com/lgcolella/gatsby-starter-developer-blog/commit/12cdfb6459a4d11554d9231ccf9e1c5d50ae046e.

I suggest you to see if it works also for your project and if not you can share the minimum snippet to reproduce the problem here.

**Comment by ahmedkrmn** [comment]
Great. I've tested it and it's working fine!
Can it be placed in the middle of the page same as ordinary pictures?

**Comment by luigi-colella** [comment]
Of course. You can use the ordinary HTML along with Markdown syntax.

Here the complete example https://github.com/lgcolella/gatsby-starter-developer-blog/commit/184df79686c8d19879f27e5cc5796852b3ce5329

**Comment by ahmedkrmn** [comment]
@lgcolella Appreciate it, thanks.
